export const featureNames=[
    "id",
    "deviceName",
    "deviceId",
    "blocklist",
    "endpoint",
    "protocolName",
    "account",
    "userDevice",
    "location",
    "status",
    "vin",
    "serial",
    "state",
    "tcuSerial",
    "tcuPortNumber",
    "iccid",
    "imfi",
    "mobileNumber",
    "deviceConnected",
    "provisionalState",
    "protocolVersion",
    "deviceTypeNumber",
    "vehicleType",
    "transmissionType",
    "operatingState",
    "disconnectedType",
    "createdBy",
    "updatedBy",
    "deviceUid"
]

export const featurePlaceholders=[
    "ID",
    "Device Name",
    "Device ID",
    "Blocklist",
    "Endpoint",
    "Protocol Name",
    "Account",
    "User Device",
    "Location",
    "Status",
    "VIN",
    "Serial",
    "State",
    "TCU Serial",
    "TCU Port Number",
    "ICCID",
    "IMFI",
    "Mobile Number",
    "Device Connected",
    "Provisional State",
    "Protocol Version",
    "Device Type Number",
    "Vehicle Type",
    "Transmission Type",
    "Operating State",
    "Disconnected Type",
    "Created By",
    "Updated By",
    "Device UID"
]

export const data=[
    {
        id: "1",
        deviceName: "dev01",
        deviceId: "d01",
        blocklist: ["d02, d03"],
        endpoint: "dev01",
        protocolName: "dev01",
        account: "ac01",
        userDevice: "dev01",
        location: "l01",
        status: "active",
        vin: "0-01",
        serial: "a-01",
        state: "good",
        tcuSerial: "001",
        tcuPortNumber: "p-001",
        iccid: "001",
        imfi: "001",
        mobileNumber: "01",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "01",
        deviceTypeNumber: "01",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "01",
        disconnectedType: "01",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "01-dev01"
    },
    {
        id: "2",
        deviceName: "dev02",
        deviceId: "d02",
        blocklist: ["d02, d03"],
        endpoint: "dev02",
        protocolName: "dev02",
        account: "ac02",
        userDevice: "dev02",
        location: "l02",
        status: "active",
        vin: "0-02",
        serial: "a-02",
        state: "good",
        tcuSerial: "002",
        tcuPortNumber: "p-002",
        iccid: "002",
        imfi: "002",
        mobileNumber: "02",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "02",
        deviceTypeNumber: "02",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "02",
        disconnectedType: "02",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "02-dev02"
    },
    {
        id: "3",
        deviceName: "dev03",
        deviceId: "d03",
        blocklist: ["d02, d03"],
        endpoint: "dev03",
        protocolName: "dev03",
        account: "ac03",
        userDevice: "dev03",
        location: "l03",
        status: "active",
        vin: "0-03",
        serial: "a-03",
        state: "good",
        tcuSerial: "003",
        tcuPortNumber: "p-003",
        iccid: "003",
        imfi: "003",
        mobileNumber: "03",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "03",
        deviceTypeNumber: "03",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "03",
        disconnectedType: "03",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "01-dev03"
    },
    {
        id: "4",
        deviceName: "dev04",
        deviceId: "d04",
        blocklist: ["d02, d03"],
        endpoint: "dev04",
        protocolName: "dev04",
        account: "ac04",
        userDevice: "dev04",
        location: "l04",
        status: "active",
        vin: "0-04",
        serial: "a-04",
        state: "good",
        tcuSerial: "004",
        tcuPortNumber: "p-004",
        iccid: "004",
        imfi: "004",
        mobileNumber: "04",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "04",
        deviceTypeNumber: "04",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "04",
        disconnectedType: "04",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "01-dev04"
    },
    {
        id: "5",
        deviceName: "dev05",
        deviceId: "d05",
        blocklist: ["d02, d03"],
        endpoint: "dev05",
        protocolName: "dev05",
        account: "ac05",
        userDevice: "dev05",
        location: "l05",
        status: "active",
        vin: "0-05",
        serial: "a-05",
        state: "good",
        tcuSerial: "005",
        tcuPortNumber: "p-005",
        iccid: "005",
        imfi: "005",
        mobileNumber: "05",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "05",
        deviceTypeNumber: "05",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "05",
        disconnectedType: "05",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "01-dev05"
    },
    {
        id: "6",
        deviceName: "dev06",
        deviceId: "d06",
        blocklist: ["d02, d03"],
        endpoint: "dev06",
        protocolName: "dev06",
        account: "ac06",
        userDevice: "dev06",
        location: "l06",
        status: "active",
        vin: "0-06",
        serial: "a-06",
        state: "good",
        tcuSerial: "006",
        tcuPortNumber: "p-006",
        iccid: "006",
        imfi: "006",
        mobileNumber: "06",
        deviceConnected: "2",
        provisionalState: true,
        protocolVersion: "06",
        deviceTypeNumber: "06",
        vehicleType: "auto",
        transmissionType: "tcp",
        operatingState: "06",
        disconnectedType: "06",
        createdBy: "pr-01",
        updatedBy: "pr-02",
        deviceUid: "01-dev06"
    }
]